# Generated by Django 3.1.4 on 2020-12-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
