# Generated by Django 3.1.2 on 2020-11-16 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0002_post_summernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernote',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelog.post'),
            preserve_default=False,
        ),
    ]
