# Generated by Django 3.1.2 on 2020-11-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0003_summernote_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummerNote',
        ),
    ]
