# Generated by Django 3.1.4 on 2020-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0003_auto_20201203_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
