# Generated by Django 3.1.2 on 2020-11-16 04:27

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.utils


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0004_delete_summernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to=django_summernote.utils.uploaded_filepath)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelog.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
