# Generated by Django 3.1.2 on 2020-11-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0005_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='post',
        ),
    ]
